# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traite', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Music'),
        ),
    ]
