# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_musicdownloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='likealbum',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 16, 5, 18, 5000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likemusic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 16, 5, 30, 317000)),
            preserve_default=False,
        ),
    ]
