# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0005_auto_20160503_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='auteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
