# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import workspace.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_auto_20160503_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='type_album',
            field=models.CharField(choices=[('AL', 'Album'), ('PL', 'Playlist'), ('SI', 'Single')], default='AL', max_length=2),
        ),
        migrations.AlterField(
            model_name='music',
            name='path',
            field=models.FileField(upload_to=workspace.models.renomage),
        ),
    ]
