# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import workspace.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20160504_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='path',
            field=models.FileField(max_length=500, upload_to=workspace.models.renomage),
        ),
    ]
